modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="dcclasses"
version="1.1.3"
displayName="DawnCraft Classes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dc-classes"
updateJSONURL=""
credits=""
authors="Smileycorp"
description="Adds a dynamic configurable classes system"
